### PR TITLE
Fix constructor breaking with format as input

### LINKED ISSUE #101: PhoneNumber constraint breaks when you ser a format
When you set a format on the phone number constraint like so:
```
    #[\Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber(
        format: PhoneNumberFormat::E164,
        type: \Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber::MOBILE,
    )]
```
it'll break with `No default option is configured for constraint \"Misd\\PhoneNumberBundle\\Validator\\Constraints\\PhoneNumber\".",`

Which is caused by 
```
        if (\is_array($format)) {
            $options = array_merge($format, $options);
        } elseif (null !== $format) {
            $options['value'] = $format;
        }
```

which I assume is some legacy stuff that probably can be removed

### PR DESCRIPTION
**Pull request by KDederichs**
Fixes #101 
Also using the constructor in tests so that doesn't happen again

### CODE REVIEW

File: src/Validator/Constraints/PhoneNumber.php [hunk 1]
```diff
@@ -54,12 +54,6 @@ class PhoneNumber extends Constraint
      */
     public function __construct($format = null, $type = null, string $defaultRegion = null, string $regionPath = null, string $message = null, array $groups = null, $payload = null, array $options = [])
     {
-        if (\is_array($format)) {
-            $options = array_merge($format, $options);
-        } elseif (null !== $format) {
-            $options['value'] = $format;
-        }
```
Comment (Nek-) [inline src/Validator/Constraints/PhoneNumber.php:61]: This looks indeed somehow wrong. Maybe it's done on purpose? cc @jderusse

**Review by Nek- — APPROVED** [review]
This PR seems to be an important fix to work with attributes.

File: src/Validator/Constraints/PhoneNumber.php (hunk 1 above)
Comment (KDederichs) [reply src/Validator/Constraints/PhoneNumber.php:61]: It kinda looks to me to be some BC code to some REALLY old SF versions (2.x maybe).
I've gone through the code trying to find any use for it but could not (tests passing without it also suggests it wasn't used anywhere).
But yeah some extra confirmation might be good

File: src/Validator/Constraints/PhoneNumber.php [hunk 2]
```diff
@@ -54,12 +54,6 @@ class PhoneNumber extends Constraint
      */
     public function __construct($format = null, $type = null, string $defaultRegion = null, string $regionPath = null, string $message = null, array $groups = null, $payload = null, array $options = [])
     {
-        if (\is_array($format)) {
-            $options = array_merge($format, $options);
-        } elseif (null !== $format) {
```
Comment (Nek-) [inline src/Validator/Constraints/PhoneNumber.php:59]: The first `if` seems to be (unfortunately) an important BC break. We are going to keep it besides it's _not great_.

The $format var is therefore not `string|array|null` but `int|array|null`.

I really think the `$options['value']` part is to drop because the `getDefaultOption` is not defined.

We should trigger a deprecation if an option array is passed instead of the format.

Finally we should add some doc to the docbloc to make the usage more clear and maybe rename the format `$formatOrOptions`.

**Review by Nek- — CHANGES_REQUESTED** [review]
I can't push on your PR (you need to enable this in the options of the PR) so I let you fix this or I will create a new PR with your work.

Thanks anyway for highlighting that, probably a lot of people hit this issue without reporting it!

**Comment by Nek-** [comment]
PHPStan failures are unrelated. (seems to be an issue from the image we use)

**Review by Nek- — APPROVED** [review]
